# Generated by Django 4.1.3 on 2023-01-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.PositiveBigIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=10)),
                ('salary', models.PositiveBigIntegerField()),
            ],
        ),
    ]
